# Generated by Django 5.1.15 on 2026-04-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="source",
            field=models.CharField(
                choices=[
                    ("walk_in", "Walk-in"),
                    ("manual", "Manual (admin)"),
                    ("telegram", "Telegram bot"),
                ],
                default="manual",
                help_text="Origin channel — walk-in, manual admin entry, or Telegram bot.",
                max_length=20,
            ),
        ),
    ]
