# Generated by Django 5.1.15 on 2026-05-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_otp_tokens_and_phone_verified"),
        ("bookings", "0002_booking_source"),
        ("branches", "0009_room_idx_room_branch_status_active"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["room", "status"], name="idx_booking_room_status"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["client", "status"], name="idx_booking_client_status"
            ),
        ),
    ]
