# Generated by Django 5.1.15 on 2026-06-15 16:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_otptoken_purpose_choices"),
        ("bookings", "0003_booking_idx_booking_room_status_and_more"),
        ("branches", "0009_room_idx_room_branch_status_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_check_out_date",
                    models.DateField(
                        help_text="The booking's check-out date *before* this extension."
                    ),
                ),
                (
                    "new_check_out_date",
                    models.DateField(
                        help_text="The check-out date this extension pushed the booking to."
                    ),
                ),
                (
                    "additional_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("canceled", "Canceled")],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Booking Extension",
                "verbose_name_plural": "Booking Extensions",
                "db_table": "booking_extensions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="branch_number",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Per-branch booking sequence (Branch A #1, Branch B #1, ...). Allocated at creation; shown in the UI as '#<branch_number>'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("telegram", "Telegram")],
                default="manual",
                help_text="Origin channel — walk-in, manual admin entry, or Telegram bot.",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("branch", "branch_number"), name="uniq_booking_branch_number"
            ),
        ),
        migrations.AddField(
            model_name="bookingextension",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extensions",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="bookingextension",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_booking_extensions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="bookingextension",
            index=models.Index(
                fields=["booking", "status"], name="idx_bk_ext_booking_status"
            ),
        ),
    ]
