# Generated by Django 5.1.15 on 2026-03-30 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CleaningTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cleaning_tasks",
                        to="accounts.staff",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleaning_tasks",
                        to="branches.branch",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleaning_tasks",
                        to="branches.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cleaning Task",
                "verbose_name_plural": "Cleaning Tasks",
                "db_table": "cleaning_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CleaningImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cleaning.cleaningtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cleaning Image",
                "verbose_name_plural": "Cleaning Images",
                "db_table": "cleaning_images",
            },
        ),
        migrations.CreateModel(
            name="AIResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=10,
                    ),
                ),
                ("feedback_text", models.TextField(blank=True, default="")),
                (
                    "ai_model_version",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_results",
                        to="cleaning.cleaningtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Result",
                "verbose_name_plural": "AI Results",
                "db_table": "ai_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cleaningtask",
            index=models.Index(
                fields=["room", "status"], name="idx_cleaning_room_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="cleaningtask",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "completed"), _negated=True),
                fields=("room",),
                name="unique_active_cleaning_task_per_room",
            ),
        ),
    ]
