# Generated by Django 5.1.15 on 2026-06-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleaning", "0002_cleaning_advanced_features"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cleaningimage",
            options={
                "ordering": ["zone", "uploaded_at"],
                "verbose_name": "Cleaning Image",
                "verbose_name_plural": "Cleaning Images",
            },
        ),
        migrations.AddField(
            model_name="airesult",
            name="confidence",
            field=models.FloatField(
                blank=True, help_text="Model self-reported confidence (0–1).", null=True
            ),
        ),
        migrations.AddField(
            model_name="airesult",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Set when the verdict was fail-closed (quota/timeout/parse).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="airesult",
            name="raw_response",
            field=models.TextField(
                blank=True, default="", help_text="Raw model JSON for audit/debugging."
            ),
        ),
        migrations.AddField(
            model_name="airesult",
            name="zones",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Per-zone breakdown: [{zone, clean, issues:[...]}, ...].",
            ),
        ),
        migrations.AddField(
            model_name="cleaningimage",
            name="byte_size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cleaningimage",
            name="captured_via",
            field=models.CharField(
                default="camera",
                help_text="camera | upload — staff submissions must be 'camera'.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="cleaningimage",
            name="height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cleaningimage",
            name="is_purged",
            field=models.BooleanField(
                default=False,
                help_text="True once the image file has been deleted by retention.",
            ),
        ),
        migrations.AddField(
            model_name="cleaningimage",
            name="phash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="64-bit perceptual hash (hex) for duplicate detection.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="cleaningimage",
            name="purged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cleaningimage",
            name="width",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cleaningimage",
            name="zone",
            field=models.CharField(
                choices=[
                    ("bed", "Bed & sleeping area"),
                    ("bathroom", "Bathroom"),
                    ("floor", "Floor & general view"),
                    ("trash", "Trash bin & surfaces"),
                    ("extra", "Extra / issue report"),
                ],
                default="extra",
                help_text="Which part of the room this photo documents.",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="cleaningtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("ai_checking", "AI Checking"),
                    ("completed", "Completed"),
                    ("retry_required", "Retry Required"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
