# Generated by Django 5.1.15 on 2026-03-30 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("branches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="The calendar date this attendance record covers."
                    ),
                ),
                (
                    "shift_type",
                    models.CharField(
                        choices=[("day", "Day"), ("night", "Night")], max_length=10
                    ),
                ),
                ("check_in", models.DateTimeField(blank=True, null=True)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("late", "Late"),
                            ("absent", "Absent"),
                        ],
                        default="absent",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "db_table": "attendance",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["account", "date"], name="idx_attendance_account_date"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("staff", "Staff"), ("admin", "Admin")], max_length=10
                    ),
                ),
                (
                    "shift_type",
                    models.CharField(
                        choices=[("day", "Day"), ("night", "Night")], max_length=10
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_shifts",
                        to="accounts.director",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_assignments",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Assignment",
                "verbose_name_plural": "Shift Assignments",
                "db_table": "shift_assignments",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("role", "admin")),
                        fields=("branch", "shift_type", "date", "role"),
                        name="unique_admin_per_shift_per_branch",
                    )
                ],
            },
        ),
    ]
