# Generated by Django 5.1.15 on 2026-03-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Used for sending Telegram Bot notifications (README 26.4).",
                max_length=64,
                null=True,
                verbose_name="Telegram Chat ID",
            ),
        ),
    ]
