# Generated by Django 5.1.15 on 2026-04-08 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_telegram_chat_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspiciousActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True,
                        help_text="Client IP address of the suspicious request.",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("failed_login", "Failed Login"),
                            ("rate_limit_exceeded", "Rate Limit Exceeded"),
                            ("unauthorized_access", "Unauthorized Access"),
                            ("abnormal_behavior", "Abnormal Behavior"),
                        ],
                        help_text="Category of suspicious activity.",
                        max_length=30,
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of occurrences within the tracking window.",
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this IP/account is currently blocked.",
                    ),
                ),
                (
                    "blocked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Auto-unblock timestamp (null = not blocked).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated account (null for anonymous requests).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspicious_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Suspicious Activity",
                "verbose_name_plural": "Suspicious Activities",
                "db_table": "suspicious_activities",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "activity_type"], name="idx_sa_ip_type"
                    ),
                    models.Index(
                        fields=["is_blocked", "blocked_until"], name="idx_sa_blocked"
                    ),
                ],
            },
        ),
    ]
