# Generated by Django 5.1.15 on 2026-04-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_suspicious_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrator",
            name="salary_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Per-person shift-rate override in UZS. If null, the admin shift rate from SystemSettings is used.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="salary_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Per-person salary override in UZS. If null, the role default from SystemSettings is used.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
