# Generated by Django 5.1.15 on 2026-04-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_client_passport_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="superadmin",
            name="is_general_manager",
            field=models.BooleanField(
                default=False,
                help_text="Marks the SuperAdmin who is also acting as General Manager (Бош менеджер — e.g. Лобар). They get a personal yearly Excel workbook visible only to themselves and the CEO.",
            ),
        ),
    ]
