# Generated by Django 5.1.15 on 2026-04-28 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_director_salary_override"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="director",
            name="salary",
        ),
        migrations.RemoveField(
            model_name="superadmin",
            name="is_general_manager",
        ),
    ]
