# Generated by Django 5.1.15 on 2026-05-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_director_salary_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="director",
            name="is_general_manager",
        ),
    ]
