# Generated by Django 5.1.15 on 2026-05-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_director_is_general_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="language",
            field=models.CharField(
                blank=True,
                default="ru",
                help_text="BCP-47-ish code (ru/uz/en); used for bot push localisation.",
                max_length=8,
                verbose_name="Preferred language",
            ),
        ),
    ]
