# Generated by Django 5.1.15 on 2026-05-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_account_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="phone_verified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True once the client has confirmed phone ownership through the Telegram bot onboarding (contact share + OTP). Required before issuing a Mini App JWT. See TELEGRAM_MINI_APP_PLAN.md §3.1.",
            ),
        ),
        migrations.CreateModel(
            name="OtpToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        help_text="E.164-formatted phone number (+998XXXXXXXXX).",
                        max_length=20,
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        help_text="SHA-256 hex digest of the OTP. Plain code is never stored.",
                        max_length=128,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("onboarding", "Onboarding"), ("relogin", "Re-login")],
                        default="onboarding",
                        max_length=20,
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of failed verify attempts; locked after 5.",
                    ),
                ),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "OTP Token",
                "verbose_name_plural": "OTP Tokens",
                "db_table": "otp_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone", "consumed_at"], name="idx_otp_phone_unused"
                    )
                ],
            },
        ),
    ]
