# Generated by Django 5.1.15 on 2026-06-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_drop_suspicious_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("onboarding", "Onboarding"),
                    ("relogin", "Re-login"),
                    ("register", "Registration"),
                    ("change_password", "Change Password"),
                    ("forgot_password", "Forgot Password"),
                ],
                default="onboarding",
                max_length=20,
            ),
        ),
    ]
