# Generated by Django 5.1.15 on 2026-04-08 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_suspicious_activity"),
        ("admin_panel", "0002_systemsettings_per_room_rate"),
        ("bookings", "0001_initial"),
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("clean", "Clean"),
                            ("damaged", "Damaged"),
                            ("needs_cleaning", "Needs Cleaning"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to="bookings.booking",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_inspections",
                        to="branches.branch",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_inspections",
                        to="accounts.administrator",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="branches.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Inspection",
                "verbose_name_plural": "Room Inspections",
                "db_table": "room_inspections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomInspectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="inspection_images/%Y/%m/%d/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="admin_panel.roominspection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Inspection Image",
                "verbose_name_plural": "Room Inspection Images",
                "db_table": "room_inspection_images",
            },
        ),
        migrations.AddIndex(
            model_name="roominspection",
            index=models.Index(
                fields=["room", "created_at"], name="idx_inspection_room_date"
            ),
        ),
    ]
