# Generated by Django 5.1.15 on 2026-04-24 18:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_roominspection_roominspectionimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="admin_shift_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Administrator's per-shift rate in UZS.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="director_fixed_salary",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2000000"),
                help_text="Director's fixed monthly salary in UZS (default 2,000,000).",
                max_digits=12,
            ),
        ),
    ]
