# Generated by Django 5.1.15 on 2026-04-24 18:57

from decimal import Decimal
from django.db import migrations, models


DEFAULTS = {
    "shift_rate": Decimal("100000"),
    "per_room_rate": Decimal("15000"),
    "admin_shift_rate": Decimal("150000"),
}


def backfill_defaults(apps, schema_editor):
    """Bump existing zero values up to the new defaults so the singleton row
    reflects sensible starting salaries instead of zeros from earlier migrations."""
    SystemSettings = apps.get_model("admin_panel", "SystemSettings")
    zero = Decimal("0")
    for obj in SystemSettings.objects.all():
        changed = False
        for field, default in DEFAULTS.items():
            if getattr(obj, field) == zero:
                setattr(obj, field, default)
                changed = True
        if changed:
            obj.save(update_fields=list(DEFAULTS.keys()))


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_systemsettings_admin_shift_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="admin_shift_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("150000"),
                help_text="Administrator's per-shift rate in UZS.",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="per_room_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15000"),
                help_text="Staff per-cleaned-room rate in UZS (used when salary mode = Per-room).",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="shift_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("100000"),
                help_text="Staff per-shift rate in UZS (used when salary mode = Shift-based).",
                max_digits=12,
            ),
        ),
        migrations.RunPython(backfill_defaults, reverse_code=migrations.RunPython.noop),
    ]
