# Generated by Django 5.1.15 on 2026-04-27 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_superadmin_is_general_manager"),
        ("admin_panel", "0005_set_default_salaries"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashsession",
            name="review_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_cash_sessions",
                to="accounts.director",
            ),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="variance_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending review"),
                    ("approved", "Approved"),
                    ("disputed", "Disputed"),
                ],
                default="approved",
                help_text="Director-review state for any cash variance recorded at close. Sessions that close with no variance default to 'approved'.",
                max_length=20,
            ),
        ),
    ]
