# Generated by Django 5.1.15 on 2026-05-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0007_systemsettings_staff_shift_rate_and_gm_bonus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="gm_bonus_percent",
        ),
    ]
