# Generated by Django 5.1.15 on 2026-04-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Hero image shown on branch cards.",
                null=True,
                upload_to="branch_images/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="roomimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Uploaded room photo (preferred).",
                null=True,
                upload_to="room_images/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Legacy external URL — kept for back-compat.",
                max_length=500,
            ),
        ),
    ]
