# Generated by Django 5.1.15 on 2026-04-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_branch_image_roomimage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Default nightly price in UZS (used for new bookings).",
                max_digits=12,
            ),
        ),
    ]
