# Generated by Django 5.1.15 on 2026-04-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0003_room_base_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="working_days_per_month",
            field=models.PositiveSmallIntegerField(
                default=26,
                help_text="Number of working days the branch counts as one full month for salary purposes. Used by the advance formula (monthly_salary / working_days_per_month × worked_days_1st_to_15th). CEO-editable. See REFACTOR_PLAN_2026_04 §3.4 / Q1.",
            ),
        ),
    ]
