# Generated by Django 5.1.15 on 2026-04-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0004_branch_working_days_per_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="monthly_expense_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Per-branch cap on approved facility expenses for the calendar month. CEO-editable. See REFACTOR_PLAN_2026_04 §7.1.",
                max_digits=14,
            ),
        ),
    ]
