# Generated by Django 5.1.15 on 2026-05-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0008_branch_location_code_label"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["branch", "status", "is_active"],
                name="idx_room_branch_status_active",
            ),
        ),
    ]
