# Generated by Django 5.1.15 on 2026-03-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("branches", "0001_initial"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="monthlyreport",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("booking", "Booking"),
                    ("payment", "Payment"),
                    ("cleaning", "Cleaning"),
                    ("shift", "Shift"),
                    ("penalty", "Penalty"),
                    ("system", "System"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyreport",
            constraint=models.UniqueConstraint(
                fields=("branch", "month", "year"), name="unique_branch_month_year"
            ),
        ),
    ]
