# Generated by Django 5.1.15 on 2026-04-08 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_monthlyreport_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitylog",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("resolved", "Resolved")],
                default="open",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="facilitylog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="penalty",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_penalties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="penalty",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="penalty",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
