# Generated by Django 5.1.15 on 2026-04-26 17:44

from django.db import migrations, models


def _migrate_legacy_types(apps, schema_editor):
    """Map legacy gas/water/electricity facility logs to 'utilities'."""
    FacilityLog = apps.get_model("reports", "FacilityLog")
    FacilityLog.objects.filter(type__in=["gas", "water", "electricity"]).update(
        type="utilities",
    )


def _noop_reverse(apps, schema_editor):
    """No-op reverse — legacy categories cannot be reconstructed."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_facilitylog_status_facilitylog_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitylog",
            name="shift_type",
            field=models.CharField(
                blank=True,
                choices=[("day", "Day"), ("night", "Night")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.RunPython(_migrate_legacy_types, _noop_reverse),
        migrations.AlterField(
            model_name="facilitylog",
            name="type",
            field=models.CharField(
                choices=[
                    ("products", "Products"),
                    ("detergents", "Detergents"),
                    ("telecom", "Telecom"),
                    ("repair", "Repair"),
                    ("utilities", "Utilities"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
