# Generated by Django 5.1.15 on 2026-04-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_adminmonthlyadjustment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penalty",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("late", "Late"), ("absence", "Absence")],
                help_text="Optional categorisation (late/absence). Free-form penalties issued by Director/CEO leave this NULL — see REFACTOR_PLAN_2026_04 §2.1.",
                max_length=10,
                null=True,
            ),
        ),
    ]
