# Generated by Django 5.1.15 on 2026-04-28 00:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _migrate_old_adjustments(apps, schema_editor):
    """REFACTOR_PLAN_2026_04 §3.7 / Q2 Option B data migration.

    Copy non-zero ``fine`` and ``bonus_plus`` rows from the legacy
    ``AdminMonthlyAdjustment`` table into the new ``SalaryAdjustment``
    one-row-per-entry table. The legacy ``advance`` column is intentionally
    discarded — advances are auto-computed by the new salary lifecycle.
    """
    Old = apps.get_model("reports", "AdminMonthlyAdjustment")
    New = apps.get_model("reports", "SalaryAdjustment")
    bulk: list = []
    for row in Old.objects.all().iterator():
        if row.fine and row.fine > 0:
            bulk.append(New(
                account_id=row.account_id,
                branch_id=row.branch_id,
                year=row.year,
                month=row.month,
                kind="penalty",
                amount=row.fine,
                reason="Migrated from legacy monthly adjustment (fine).",
                created_by_id=row.updated_by_id,
                created_at=row.updated_at or row.created_at,
            ))
        if row.bonus_plus and row.bonus_plus > 0:
            bulk.append(New(
                account_id=row.account_id,
                branch_id=row.branch_id,
                year=row.year,
                month=row.month,
                kind="bonus_plus",
                amount=row.bonus_plus,
                reason="Migrated from legacy monthly adjustment (bonus +).",
                created_by_id=row.updated_by_id,
                created_at=row.updated_at or row.created_at,
            ))
    if bulk:
        New.objects.bulk_create(bulk)


def _noop_reverse(apps, schema_editor):
    # The legacy table is dropped immediately after this migration;
    # there is no meaningful reverse path. A no-op keeps `migrate <prev>`
    # callable for testing.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0004_branch_working_days_per_month"),
        ("reports", "0006_penalty_type_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("penalty", "Penalty (Жарима)"),
                            ("bonus_plus", "Bonus + (Бонус +)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Required free-form explanation. See REFACTOR_PLAN_2026_04 §3.7."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_adjustments",
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_salary_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Adjustment",
                "verbose_name_plural": "Salary Adjustments",
                "db_table": "salary_adjustments",
                "ordering": ["-year", "-month", "-created_at"],
            },
        ),
        migrations.RunPython(_migrate_old_adjustments, _noop_reverse),
        migrations.DeleteModel(
            name="AdminMonthlyAdjustment",
        ),
        migrations.AddIndex(
            model_name="salaryadjustment",
            index=models.Index(
                fields=["branch", "year", "month"],
                name="salary_adju_branch__a0be05_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salaryadjustment",
            index=models.Index(
                fields=["account", "year", "month"],
                name="salary_adju_account_cfc278_idx",
            ),
        ),
    ]
