# Generated by Django 5.1.15 on 2026-04-28 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_director_salary_override"),
        ("reports", "0007_salaryadjustment_delete_adminmonthlyadjustment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitylog",
            name="approval_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="facilitylog",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facilitylog",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_facility_logs",
                to="accounts.superadmin",
            ),
        ),
        migrations.AddField(
            model_name="facilitylog",
            name="over_limit_justified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facilitylog",
            name="over_limit_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="facilitylog",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facilitylog",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Cash (branch drawer)"),
                    ("card", "Branch card (CEO swipe)"),
                ],
                help_text="Set by CEO at approval time. Drives cash-vs-card subtotals.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="facilitylog",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facilitylog",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_facility_logs",
                to="accounts.superadmin",
            ),
        ),
        migrations.AddField(
            model_name="facilitylog",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="facilitylog",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Director who filed this expense request.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_facility_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="facilitylog",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="facilitylog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved_cash", "Approved (cash)"),
                    ("approved_card", "Approved (card)"),
                    ("rejected", "Rejected"),
                    ("paid", "Paid"),
                    ("resolved", "Resolved"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
