# Generated by Django 5.1.15 on 2026-03-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("bookings", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedStripeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        help_text="Stripe event ID (evt_...)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Stripe event type (e.g. payment_intent.succeeded)",
                        max_length=100,
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Processed Stripe Event",
                "verbose_name_plural": "Processed Stripe Events",
                "db_table": "processed_stripe_events",
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_intent_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe PaymentIntent ID (pi_...)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_event_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe event that confirmed this payment",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_intent_id"], name="idx_payment_intent_id"
            ),
        ),
    ]
