# Generated by Django 5.1.15 on 2026-04-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_salaryauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("terminal", "Terminal (POS)"),
                    ("qr", "QR Code"),
                    ("card_transfer", "Transfer to Card"),
                ],
                default="cash",
                help_text="How the money physically moved — cash / terminal / QR / card transfer.",
                max_length=20,
            ),
        ),
    ]
