# Generated by Django 5.1.15 on 2026-04-28 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payment_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salaryrecord",
            name="kind",
            field=models.CharField(
                choices=[("advance", "Advance"), ("final", "Final")],
                default="final",
                help_text="Lifecycle marker — 'advance' rows are paid days 15–20 of month M; 'final' rows are paid days 1–5 of month M+1. See REFACTOR_PLAN_2026_04 §3.6.",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="salaryrecord",
            constraint=models.UniqueConstraint(
                fields=("account", "period_start", "period_end", "kind"),
                name="unique_salary_record_per_account_period_kind",
            ),
        ),
    ]
