# Generated by Django 5.1.15 on 2026-05-04 22:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_otp_tokens_and_phone_verified"),
        ("bookings", "0002_booking_source"),
        ("branches", "0008_branch_location_code_label"),
        ("payments", "0005_salaryrecord_kind_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="uzs", max_length=8)),
                (
                    "payment_intent_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="originating_draft",
                        to="bookings.booking",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="branches.branch",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_drafts",
                        to="accounts.client",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="branches.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Draft",
                "verbose_name_plural": "Booking Drafts",
                "db_table": "booking_drafts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "status"], name="idx_draft_client_status"
                    ),
                    models.Index(fields=["expires_at"], name="idx_draft_expires_at"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExtensionDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("new_check_out_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="uzs", max_length=8)),
                (
                    "payment_intent_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_drafts",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extension Draft",
                "verbose_name_plural": "Extension Drafts",
                "db_table": "extension_drafts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["booking", "status"], name="idx_ext_booking_status"
                    )
                ],
            },
        ),
    ]
