# Generated by Django 5.1.15 on 2026-05-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_bookingdraft_extensiondraft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incomerule",
            name="shift_type",
        ),
    ]
